### ISSUE TITLE
providing a bad -c config_file produces an exception rather than an error

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#122]
**Describe the bug**
```
(suzieq) jpiet@a1:/tmp/pycharm_project_304/suzieq$ python3 suzieq/cli/suzieq-cli -c ~/suzieq-data.yml
Traceback (most recent call last):
  File "/home/jpiet/.local/share/virtualenvs/suzieq-zI29E9ll/src/python-nubia/nubia/internal/io/eventbus.py", line 24, in react
    self.on_connected(*args, **kwargs)
  File "/tmp/pycharm_project_304/suzieq/suzieq/cli/sq_nubia_context.py", line 28, in on_connected
    config_file=self._args.config)
  File "/tmp/pycharm_project_304/suzieq/suzieq/utils.py", line 70, in load_sq_config
    with open(cfgfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jpiet/suzieq-data.yml'
Traceback (most recent call last):
  File "/home/jpiet/.local/share/virtualenvs/suzieq-zI29E9ll/src/python-nubia/nubia/internal/io/eventbus.py", line 24, in react
    self.on_connected(*args, **kwargs)
  File "/tmp/pycharm_project_304/suzieq/suzieq/cli/sq_nubia_context.py", line 28, in on_connected
    config_file=self._args.config)
  File "/tmp/pycharm_project_304/suzieq/suzieq/utils.py", line 70, in load_sq_config
    with open(cfgfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jpiet/suzieq-data.yml'
jpiet>
```

**Comment by ddutt** [comment]
This should not happen anymore. Various fixes to address this. Here are some examples:
```
(suzieq-7LyZwL87-py3.7) ddutt@ddutt-yoga:~/work/suzieq$ suzieq/cli/sq_cli.py -c /tmp/foo.yml
ERROR: Unable to open config file /tmp/foo.yml: No such file or directory
(suzieq-7LyZwL87-py3.7) 1 ddutt@ddutt-yoga:~/work/suzieq$ touch /tmp/foo.yml
(suzieq-7LyZwL87-py3.7) ddutt@ddutt-yoga:~/work/suzieq$ suzieq/cli/sq_cli.py -c /tmp/foo.yml
ERROR: Empty config file /tmp/foo.yml
(suzieq-7LyZwL87-py3.7) ddutt@ddutt-yoga:~/work/suzieq$ suzieq/cli/sq_cli.py -c /tmp/foo.yml
ERROR: Invalid config file: /tmp/foo.yml
FATAL: Invalid config file format
(suzieq-7LyZwL87-py3.7) 1 ddutt@ddutt-yoga:~/work/suzieq$ suzieq/cli/sq_cli.py -c /tmp/foo.yml
ERROR: Invalid config file: /tmp/foo.yml
FATAL: No data directory for output files specified
```

Here is the latest commit to address this: 540d7626b632562ab8eb7795199a652adc8f1549
