### ISSUE TITLE
cli for command with no data in table, column filter and json output produces exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#124]
**Describe the bug**
if you have a table that does not exist and use that command with the columns filter and json output if produces an exception

**To Reproduce**
there is no ospf in this parquet-out database
```(suzieq-dev) jpiet@a1:~/suzieq-dev$ python3 suzieq/cli/suzieq-cli -c ~/update_data.yml evpnVni show --columns=hostname --format=json
Error running command: "None of [Index(['hostname'], dtype='object')] are in the [columns]"
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpiet/.local/share/virtualenvs/suzieq-dev-yl0d4M2C/src/python-nubia/nubia/internal/cmdbase.py", line 446, in run_cli
    return fn(**kwargs)
  File "/home/jpiet/suzieq-dev/suzieq/cli/sqcmds/EvpnVniCmd.py", line 56, in show
    return self._gen_output(df)
  File "/home/jpiet/suzieq-dev/suzieq/cli/sqcmds/command.py", line 130, in _gen_output
    print(df[cols].to_json(orient=json_orient))
  File "/home/jpiet/.local/share/virtualenvs/suzieq-dev-yl0d4M2C/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/jpiet/.local/share/virtualenvs/suzieq-dev-yl0d4M2C/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/home/jpiet/.local/share/virtualenvs/suzieq-dev-yl0d4M2C/lib/python3.7/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['hostname'], dtype='object')] are in the [columns]"
------------------------------------------------------------
(suzieq-dev) jpiet@a1:~/suzieq-dev$ 
```
**Expected behavior**
without json output it looks like this
```
(suzieq-dev) jpiet@a1:~/suzieq-dev$ python3 suzieq/cli/suzieq-cli -c ~/update_data.yml evpnVni show --columns=hostname
Empty DataFrame
Columns: []
Index: []
```

**Comment by ddutt** [comment]
Fixed with commit bfdd1f0244b49acd0112e8822e662df6f14b067b
