### ISSUE TITLE
even with latest data, route show --columns=hostname failes

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#136]
**Describe the bug**
```
[255 rows x 11 columns]
jpiet> route show columns=hostname
Error running command: "['ipvers'] not in index"
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/src/python-nubia/nubia/internal/cmdbase.py", line 372, in run_interactive
    ret = fn(**args_dict)
  File "/home/jpiet/suzieq-dev/suzieq/cli/sqcmds/RouteCmd.py", line 118, in show
    prefixlen=prefixlen,
  File "/home/jpiet/suzieq-dev/suzieq/sqobjects/basicobj.py", line 109, in get
    return self.engine_obj.get(**kwargs)
  File "/home/jpiet/suzieq-dev/suzieq/engines/pandas/routes.py", line 12, in get
    df = super().get(**kwargs)
  File "/home/jpiet/suzieq-dev/suzieq/engines/pandas/engineobj.py", line 71, in get
    df = self.get_valid_df(self.iobj._table, sort_fields, **kwargs)
  File "/home/jpiet/suzieq-dev/suzieq/engines/pandas/engineobj.py", line 56, in get_valid_df
    **kwargs
  File "/home/jpiet/suzieq-dev/suzieq/engines/pandas/engine.py", line 193, in get_table_df
    return final_df[fields]
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/indexing.py", line 1646, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['ipvers'] not in index"
------------------------------------------------------------
```

**Comment by jopietsch** [comment]
fixed
