### ISSUE TITLE
route lpm error: Error running command: name 'ipvers' is not defined

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#137]
**Describe the bug**
```
(suzieq-jHSpqB0P-py3.7) jpiet@b2:~/suzieq-dev$ python suzieq/cli/suzieq-cli -c ~/basic_dual_bgp.yml route lpm --address=10.0.0.1
Error running command: name 'ipvers' is not defined
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/scope.py", line 187, in resolve
    return self.resolvers[key]
  File "/home/jpiet/.pyenv/versions/3.7.7/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/jpiet/.pyenv/versions/3.7.7/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'ipvers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/scope.py", line 198, in resolve
    return self.temps[key]
KeyError: 'ipvers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/src/python-nubia/nubia/internal/cmdbase.py", line 446, in run_cli
    return fn(**kwargs)
  File "/home/jpiet/suzieq-dev/suzieq/cli/sqcmds/RouteCmd.py", line 159, in lpm
    namespace=self.namespace,
  File "/home/jpiet/suzieq-dev/suzieq/sqobjects/routes.py", line 24, in lpm
    return self.engine_obj.lpm(**kwargs)
  File "/home/jpiet/suzieq-dev/suzieq/engines/pandas/routes.py", line 95, in lpm
    df = self.get_valid_df(self.iobj._table, sort_fields, **kwargs)
  File "/home/jpiet/suzieq-dev/suzieq/engines/pandas/engineobj.py", line 56, in get_valid_df
    **kwargs
  File "/home/jpiet/suzieq-dev/suzieq/engines/pandas/engine.py", line 161, in get_table_df
    .query(query_str)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 3231, in query
    res = self.eval(expr, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 3346, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/eval.py", line 332, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 764, in __init__
    self.terms = self.parse()
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 781, in parse
    return self._visitor.visit(self.expr)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 381, in visit_Module
    return self.visit(expr, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 384, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 676, in visit_Compare    return self.visit(binop)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 497, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 416, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 510, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/ops.py", line 82, in __init__
    self._value = self._resolve_name()
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/ops.py", line 99, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-jHSpqB0P-py3.7/lib/python3.7/site-packages/pandas/core/computation/scope.py", line 203, in resolve
    raise UndefinedVariableError(key, is_local)
pandas.core.computation.ops.UndefinedVariableError: name 'ipvers' is not defined
```

**Comment by jopietsch** [comment]
fixed
