### ISSUE TITLE
with CNDCN evpn ospf-ibgp vagrant, sq-poller cdrashes

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#138]
**Describe the bug**
```
(suzieq-jHSpqB0P-py3.7) jpiet@b2:~/suzieq-dev$ rm -rf /mnt/suzieq/parquet-out/* ; python suzieq/poller/sq-poller -i ~/cloud-native-data-center-networking/topologies/dual-attach/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory -n ospf-ibgp
Traceback (most recent call last):
  File "suzieq/poller/sq-poller", line 191, in <module>
    asyncio.run(start_poller(userargs, cfg))
  File "/home/jpiet/.pyenv/versions/3.7.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "suzieq/poller/sq-poller", line 131, in start_poller
    await asyncio.gather(*tasks)
  File "/home/jpiet/suzieq-dev/suzieq/poller/services/service.py", line 565, in run
    result = self.process_data(output)
  File "/home/jpiet/suzieq-dev/suzieq/poller/services/service.py", line 353, in process_data
    result = self.merge_results(result_list, data)
  File "/home/jpiet/suzieq-dev/suzieq/poller/services/service.py", line 370, in merge_results
    key = '-'.join(keyvals)
TypeError: sequence item 0: expected str instance, int found

```

**Comment by jopietsch** [comment]
it's evpnvni:
```
(suzieq-jHSpqB0P-py3.7) jpiet@b2:~/suzieq-dev$ python suzieq/poller/sq-poller -i ~/cloud-native-data-center-networking/topologies/dual-attach/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory -n ospf-ibgp -s evpnVni
Traceback (most recent call last):
  File "suzieq/poller/sq-poller", line 191, in <module>
    asyncio.run(start_poller(userargs, cfg))
  File "/home/jpiet/.pyenv/versions/3.7.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "suzieq/poller/sq-poller", line 131, in start_poller
    await asyncio.gather(*tasks)
  File "/home/jpiet/suzieq-dev/suzieq/poller/services/service.py", line 565, in run
    result = self.process_data(output)
  File "/home/jpiet/suzieq-dev/suzieq/poller/services/service.py", line 353, in process_data
    result = self.merge_results(result_list, data)
  File "/home/jpiet/suzieq-dev/suzieq/poller/services/service.py", line 370, in merge_results
    key = '-'.join(keyvals)
TypeError: sequence item 0: expected str instance, int found
```
