### ISSUE TITLE
route lpm for IPv6 with hostname filter raises exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#142]
**Describe the bug**
```
jpiet> route lpm address='2001:db8:0:1::101' hostname=server101
Error running command: unhashable type: 'IPNetworkArray'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/src/python-nubia/nubia/internal/cmdbase.py", line 372, in run_interactive
    ret = fn(**args_dict)
  File "/home/jpiet/suzieq/suzieq/cli/sqcmds/RouteCmd.py", line 160, in lpm
    namespace=self.namespace,
  File "/home/jpiet/suzieq/suzieq/sqobjects/routes.py", line 24, in lpm
    return self.engine_obj.lpm(**kwargs)
  File "/home/jpiet/suzieq/suzieq/engines/pandas/routes.py", line 117, in lpm
    return idx.merge(df)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 7297, in merge
    validate=validate,
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 88, in merge
    return op.get_result()
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 643, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 862, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 841, in _get_join_indexers
    self.left_join_keys, self.right_join_keys, sort=self.sort, how=self.how
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1311, in _get_join_indexers
    zipped = zip(*mapped)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1309, in <genexpr>
    for n in range(len(left_keys))
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1918, in _factorize_keys
    rlab = rizer.factorize(rk)
  File "pandas/_libs/hashtable.pyx", line 77, in pandas._libs.hashtable.Factorizer.factorize
  File "pandas/_libs/hashtable_class_helper.pxi", line 1822, in pandas._libs.hashtable.PyObjectHashTable.get_labels
  File "pandas/_libs/hashtable_class_helper.pxi", line 1731, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'IPNetworkArray'
------------------------------------------------------------
```
**Expected behavior**
for v4 it looks like
```
jpiet> route lpm address='172.16.1.101' hostname=server101                                                                                                                                                                                                 Error: 1  namespace   hostname      vrf                             prefix nexthopIps     oifs protocol        source  metric  ipvers   action               timestamp
0  dual-bgp  server101  default  IPNetworkArray(['172.16.1.0/24'])         []  [bond0]   kernel  172.16.1.101      20       4  forward 2020-06-13 03:45:52.015
```

**Comment by jopietsch** [comment]
fixed
