### ISSUE TITLE
with nxos data, bgp assert produces exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#150]
**Describe the bug**
```
jpiet> bgp assert
Error running command: index 0 is out of bounds for axis 0 with size 0
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/src/python-nubia/nubia/internal/cmdbase.py", line 372, in run_interactive
    ret = fn(**args_dict)
  File "/home/jpiet/suzieq/suzieq/cli/sqcmds/BgpCmd.py", line 107, in aver
    namespace=self.namespace,
  File "/home/jpiet/suzieq/suzieq/sqobjects/bgp.py", line 23, in aver
    return self.engine_obj.aver(**kwargs)
  File "/home/jpiet/suzieq/suzieq/engines/pandas/bgp.py", line 148, in aver
    df['cif'] = df.apply(self._get_connect_if, axis=1)
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/apply.py", line 313, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/apply.py", line 341, in apply_series_generator
    results[i] = self.f(v)
  File "/home/jpiet/suzieq/suzieq/engines/pandas/bgp.py", line 22, in _get_connect_if
    val = rslt['oifs'][0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
------------------------------------------------------------
```

**Comment by jopietsch** [comment]
I think everything else in bgp works
```
jpiet> bgp summarize                                                                                                                  Error: 1                                                                nxos
deviceCnt                                                          4
totalPeerCnt                                                       8
uniqueAsnCnt                                                       1
uniqueVrfsCnt                                                      1
failedPeerCnt                                                      0
upTimeStat         [2 days 15:37:58, 2 days 15:38:04, 2 days 15:3...
v4PfxRxStat                                                [0, 0, 0]
v6PfxRxStat                                                [0, 0, 0]
evpnPfxRxStat                                              [5, 7, 6]
updatesRxStat                                      [367, 476, 414.5]
updatesTxStat                                      [367, 476, 414.5]
activeAfiSafiList                                       [ipv4, evpn]
```
