### ISSUE TITLE
nxos data, no lldp data, lldp show columns=hostname --format=json produces exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#151]
**Describe the bug**

This probably effects any table without data

```
(suzieq-ITL68y-d-py3.7) jpiet@a2:~/suzieq$ python3 suzieq/cli/suzieq-cli -c ~/configs/nxos.yml lldp show --columns=hostname --format=json
Error running command: "None of [Index(['hostname'], dtype='object')] are in the [columns]"
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/src/python-nubia/nubia/internal/cmdbase.py", line 446, in run_cli
    return fn(**kwargs)
  File "/home/jpiet/suzieq/suzieq/cli/sqcmds/LldpCmd.py", line 56, in show
    return self._gen_output(df)
  File "/home/jpiet/suzieq/suzieq/cli/sqcmds/command.py", line 128, in _gen_output
    print(df[cols].to_json(orient=json_orient))
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/home/jpiet/.cache/pypoetry/virtualenvs/suzieq-ITL68y-d-py3.7/lib/python3.7/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['hostname'], dtype='object')] are in the [columns]"
```
**Expected behavior**
if I don't add --format=json, it works
```
(suzieq-ITL68y-d-py3.7) jpiet@a2:~/suzieq$ python3 suzieq/cli/suzieq-cli -c ~/configs/nxos.yml lldp show --columns=hostname
Empty DataFrame
Columns: []
Index: []
```

**Comment by jopietsch** [comment]
mlag does the same thing because in the captured nxos there is no data in that table either.
