### ISSUE TITLE
with latest junos data, ospf assert raises exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#166]
**Describe the bug**
```
(suzieq-QZqWZG2D-py3.8) jpietsch@jpietsch-server:~/suzieq$ python3 suzieq/cli/suzieq-cli -c ~/configs/junos.yml ospf assert
Error running command: 'routerId'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/src/python-nubia/nubia/internal/cmdbase.py", line 446, in run_cli
    return fn(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/OspfCmd.py", line 106, in aver
    df = self.sqobj.aver(
  File "/home/jpietsch/suzieq/suzieq/sqobjects/ospf.py", line 43, in aver
    return self.engine_obj.aver(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/ospf.py", line 177, in aver
    ospf_df.merge(df, on=["routerId"], how="outer")
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 7284, in merge
    return merge(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 73, in merge
    op = _MergeOperation(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 627, in __init__
    ) = self._get_merge_keys()
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 983, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 1692, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'routerId'
```

I rolled back code, while changing data and it didn't fix it, and I kept the most top of the tree code while going to previous data and it broke, so it's something about the data.

**Comment by ddutt** [comment]
Fixed with commit fe6a2c27ed246305764f83f271d472e0df86e8cb
