### ISSUE TITLE
ospf summarize crash

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#188]
```
oot> ospf summarize                                                                                                                                                                                         
Error running command: 'G1'
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4411, in get_value
    return libindex.get_value_at(s, key)
  File "pandas/_libs/index.pyx", line 44, in pandas._libs.index.get_value_at
  File "pandas/_libs/index.pyx", line 45, in pandas._libs.index.get_value_at
  File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
  File "pandas/_libs/util.pxd", line 83, in pandas._libs.util.validate_indexer
TypeError: 'str' object cannot be interpreted as an integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/src/python-nubia/nubia/internal/cmdbase.py", line 372, in run_interactive
    ret = fn(**args_dict)
  File "/root/.local/lib/python3.7/site-packages/suzieq/cli/sqcmds/OspfCmd.py", line 95, in summarize
    self._init_summarize()
  File "/root/.local/lib/python3.7/site-packages/suzieq/cli/sqcmds/command.py", line 201, in _init_summarize
    namespace=self.namespace,
  File "/root/.local/lib/python3.7/site-packages/suzieq/sqobjects/ospf.py", line 35, in summarize
    return self.engine_obj.summarize(**kwargs)
  File "/root/.local/lib/python3.7/site-packages/suzieq/engines/pandas/ospf.py", line 127, in summarize
    self._gen_summarize_data()
  File "/root/.local/lib/python3.7/site-packages/suzieq/engines/pandas/engineobj.py", line 175, in _gen_summarize_data
    self._add_stats_to_summary(statfld, field_name)
  File "/root/.local/lib/python3.7/site-packages/suzieq/engines/pandas/engineobj.py", line 362, in _add_stats_to_summary
    for i in self.ns.keys()}
  File "/root/.local/lib/python3.7/site-packages/suzieq/engines/pandas/engineobj.py", line 362, in <setcomp>
    for i in self.ns.keys()}
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 871, in __getitem__
    result = self.index.get_value(self, key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4419, in get_value
    raise e1
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4405, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 90, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'G1'
```

**Comment by ddutt** [comment]
@anubisg1 I can't reproduce this issue. Can you please try and let me know if you're still running into it?

**Comment by anubisg1** [comment]
Unable to reproduce
