### ISSUE TITLE
Juniper timestamps causing sq-poller failure

### ISSUE THREAD

**Issue by stalloneclone** [netenglabs/suzieq#194]
It appears that the function get_timestamp_from_junos_time() in utils.py used by the ospfNbr and bgp poller services fails to properly handle/parse juniper timestamps that use `weeks` in the timestamp i.e. (24w6d 19:13:37).

Here is the traceback:

```Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/sq-poller", line 191, in <module>
    asyncio.run(start_poller(userargs, cfg))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/sq-poller", line 131, in start_poller
    await asyncio.gather(*tasks)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 578, in run
    result = self.process_data(output)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 354, in process_data
    return self.clean_data(result, data)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/services/ospfNbr.py", line 39, in clean_data
    processed_data = self._clean_junos_data(processed_data, raw_data)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/services/ospfNbr.py", line 87, in _clean_junos_data
    entry['lastChangeTime'], raw_data[0]['timestamp']/1000)
  File "/root/.local/lib/python3.7/site-packages/suzieq/utils.py", line 414, in get_timestamp_from_junos_time
    days = int(days)
ValueError: invalid literal for int() with base 10: '24w6'```

**Comment by ddutt** [comment]
Hi @stalloneclone , thanks for engaging.

This should be a trivial fix. Do you have examples of timestamp formats used by Junos?

Thanks,

Dinesh

**Comment by stalloneclone** [comment]
Hi Dinesh!

Unfortunately I haven't found any juniper docs that explicitly define how ospf neighbor and bgp neighbor elapsed time is formatted.  I think it is safe to assume that junos will convert`365d` to `1y` in the elapsed timestamp.  So I suppose the integer for `y` and `w` needs to be handled here https://github.com/netenglabs/suzieq/blob/master/suzieq/utils.py#L410 and delta needs to be updated for the new values.

**Comment by ddutt** [comment]
@stalloneclone : Can you pull ddutt/suzieq:prerc and try it out. It should have the problem fixed. I'll checkin the fix after you verify.

**Comment by stalloneclone** [comment]
@ddutt looks good! I am no longer seeing that timestamp error when polling juniper devices.
