### ISSUE TITLE
BGP polling crash on Junos

### ISSUE THREAD

**Issue by fdebonneval** [netenglabs/suzieq#227]
**Describe the bug**
sq-poller throws an error at runtime

**To Reproduce**
1. run `sq-poller -D inventory -s bgp`
2. Watch the logfile and wait for the error

**Expected behavior**
Poller should not throw errors ^^

**Log**
```
2020-07-27 14:23:16,306 - asyncssh - INFO - [conn=1, chan=18] Received exit status 0
2020-07-27 14:23:16,313 - asyncssh - INFO - [conn=1, chan=18] Received channel close
2020-07-27 14:23:16,316 - asyncssh - INFO - [conn=1, chan=18] Channel closed
2020-07-27 14:23:16,323 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<Service.run() done, defined at /root/.local/lib/python3.7/site-packages/suzieq/poller/services/service.py:540> exception=AttributeError("'NoneType' object has no attribute 'split'")>
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 604, in run
    result = self.process_data(output)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 355, in process_data
    return self.clean_data(result, data)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/services/bgp.py", line 19, in clean_data
    processed_data = self._clean_junos_data(processed_data, raw_data)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/services/bgp.py", line 86, in _clean_junos_data
    for afi in entry['afiSafiAdvList'].split():
AttributeError: 'NoneType' object has no attribute 'split'
```

**Additional context**
Target system is an MX router running Junos 14.2

**Comment by ddutt** [comment]
Resolved with commits separating junos into junos-qfx, junos-mx etc.
