### ISSUE TITLE
fs summarize produces exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#232]
**Describe the bug**
I think it's not been implemented at all. So we need to implement something here.

```
jpietsch> fs summarize
Error running command: 'deviceCnt'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/src/python-nubia/nubia/internal/cmdbase.py", line 372, in run_interactive
    ret = fn(**args_dict)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/command.py", line 171, in summarize
    self._init_summarize()
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/command.py", line 200, in _init_summarize
    self.summarize_df = self.sqobj.summarize(
  File "/home/jpietsch/suzieq/suzieq/sqobjects/basicobj.py", line 118, in summarize
    return self.engine_obj.summarize(namespace=namespace)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/engineobj.py", line 133, in summarize
    self._post_summarize()
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/engineobj.py", line 302, in _post_summarize
    if self.ns[ns][check_empty_col] == 0:
KeyError: 'deviceCnt'
------------------------------------------------------------
```

**Comment by ddutt** [comment]
Fixed with commit 1515a4e05ddfaedce867836c2a160a6b0fcba45e and 986b94198ec1e2f75554cefb18d86d990cad4762
