### ISSUE TITLE
add information about adding to known_devtypes in adding-a-new-nos docs

### ISSUE THREAD

**Issue by dt-arrcus** [netenglabs/suzieq#252]
**Describe the bug**

The `adding-a-new-nos` docs might want to add a new step to add the new NOS value to known_devtypes list in the utlis.py file.  Otherwise the following exception is thrown if the devtype doesn't exist:

```
root@b376e31d85e0:/suzieq# sq-poller -D inventory.yml
arcos
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/sq-poller", line 259, in <module>
    asyncio.run(start_poller(userargs, cfg))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/sq-poller", line 127, in start_poller
    nodes, svcs = await asyncio.gather(*tasks)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/nodes/node.py", line 113, in init_hosts
    newnode = await f
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 560, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/nodes/node.py", line 206, in _init
    self.set_devtype(devtype)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/nodes/node.py", line 254, in set_devtype
    raise ValueError
```

**Comment by ddutt** [comment]
Thanks. You can do the same by updating the document and issuing a PR. But I'll fix it.
