### ISSUE TITLE
evpnVni show returns exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#260]
using the multidc data
```
(suzieq-old-UPXhMpvs-py3.8) jpietsch@jpietsch-server:~/trial/suz$ suzieq/cli/suzieq-cli -c ~/configs/multidc.yml evpnVni show
Error running command: 'namespace'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-old-UPXhMpvs-py3.8/src/python-nubia/nubia/internal/cmdbase.py", line 446, in run_cli
    return fn(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/EvpnVniCmd.py", line 49, in show
    df = self.sqobj.get(
  File "/home/jpietsch/suzieq/suzieq/sqobjects/basicobj.py", line 136, in get
    return self.engine_obj.get(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/evpnVni.py", line 53, in get
    df = df.merge(ifdf, on=['namespace', 'hostname', 'ifname',
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-old-UPXhMpvs-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 7284, in merge
    return merge(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-old-UPXhMpvs-py3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 73, in merge
    op = _MergeOperation(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-old-UPXhMpvs-py3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 627, in __init__
    ) = self._get_merge_keys()
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-old-UPXhMpvs-py3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 983, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-old-UPXhMpvs-py3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 1692, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'namespace'

```

this is on master

**Comment by jopietsch** [comment]
I can't reproduce. I have no idea what was going on or what changed.
