### ISSUE TITLE
bgp show columns I forget namespace get an exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#295]
**Describe the bug**
```
jpietsch> bgp show columns='hostname peer peerHostname asn peerAsn v4PfxRx v4PfxTx'
Error running command: 'namespace'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/src/python-nubia/nubia/internal/cmdbase.py", line 408, in run_interactive
    ret = fn(**args_dict)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/BgpCmd.py", line 75, in show
    df = self.sqobj.get(
  File "/home/jpietsch/suzieq/suzieq/sqobjects/basicobj.py", line 155, in get
    return self.engine_obj.get(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/bgp.py", line 44, in get
    mdf = self._get_peer_matched_df(df)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/bgp.py", line 156, in _get_peer_matched_df
    mestd_df = estd_df.merge(estd_df, left_on=['namespace', 'peerIP'],
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 7950, in merge
    return merge(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 74, in merge
    op = _MergeOperation(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 652, in __init__
    ) = self._get_merge_keys()
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1005, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 1563, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'namespace'
```

**Comment by ddutt** [comment]
Closed with commit bb4790e375ca5024e64c9abd259ebfb060b33698
