### ISSUE TITLE
bgp show columns forget to add vrf, get an exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#296]
**Describe the bug**
------------------------------------------------------------
```
jpietsch> bgp show columns='namespace hostname peer peerHostname asn peerAsn v4PfxRx v4PfxTx'                                                                         Error: 1Error running command: Index(['vrf'], dtype='object')
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/src/python-nubia/nubia/internal/cmdbase.py", line 408, in run_interactive
    ret = fn(**args_dict)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/BgpCmd.py", line 75, in show
    df = self.sqobj.get(
  File "/home/jpietsch/suzieq/suzieq/sqobjects/basicobj.py", line 155, in get
    return self.engine_obj.get(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/bgp.py", line 44, in get
    mdf = self._get_peer_matched_df(df)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/bgp.py", line 156, in _get_peer_matched_df
    mestd_df = estd_df.merge(estd_df, left_on=['namespace', 'peerIP'],
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 5112, in drop_duplicates
    duplicated = self.duplicated(subset, keep=keep)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 5248, in duplicated
    raise KeyError(diff)
KeyError: Index(['vrf'], dtype='object')
------------------------------------------------------------
```

**Comment by ddutt** [comment]
Fixed by one of the commits  for the 0.8 release, probably bb4790e375ca5024e64c9abd259ebfb060b33698
