### ISSUE TITLE
table with mostly routes (no protocols) vlan summarize produces Exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#298]
**Describe the bug**
```
(suzieq-QZqWZG2D-py3.8) jpietsch@jpietsch-server:~/suzieq$ suzieq/cli/suzieq-cli vlan summarize
Error running command: unhashable type: 'numpy.ndarray'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/src/python-nubia/nubia/internal/cmdbase.py", line 482, in run_cli
    return fn(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/command.py", line 219, in summarize
    self._init_summarize()
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/command.py", line 244, in _init_summarize
    self.summarize_df = self.sqobj.summarize(
  File "/home/jpietsch/suzieq/suzieq/sqobjects/basicobj.py", line 169, in summarize
    return self.engine_obj.summarize(namespace=namespace,
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/vlan.py", line 53, in summarize
    self._gen_summarize_data()
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/engineobj.py", line 178, in _gen_summarize_data
    self._add_field_to_summary(col, function, field_name)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/engineobj.py", line 376, in _add_field_to_summary
    field_per_ns = getattr(self.nsgrp[field], method)()
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 637, in nunique
    codes, _ = algorithms.factorize(val, sort=False)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/algorithms.py", line 677, in factorize
    codes, uniques = _factorize_array(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/algorithms.py", line 500, in _factorize_array
    uniques, codes = table.factorize(
  File "pandas/_libs/hashtable_class_helper.pxi", line 1873, in pandas._libs.hashtable.PyObjectHashTable.factorize
  File "pandas/_libs/hashtable_class_helper.pxi", line 1787, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'numpy.ndarray'
------------------------------------------------------------
```

vlan show works fine

**Comment by ddutt** [comment]
This is because this older format of VLAN table is not supported. We changed it to the newer format post 0.6 release. This is the only table that is affected this way.
