### ISSUE TITLE
in older data, device show produces exception: TypeError: unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#301]
**Describe the bug**
```
jpietsch> device show
Error running command: unsupported operand type(s) for /: 'str' and 'int'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/src/python-nubia/nubia/internal/cmdbase.py", line 408, in run_interactive
    ret = fn(**args_dict)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/DeviceCmd.py", line 66, in show
    df = self._get()
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/DeviceCmd.py", line 46, in _get
    df = self.sqobj.get(
  File "/home/jpietsch/suzieq/suzieq/sqobjects/basicobj.py", line 155, in get
    return self.engine_obj.get(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/device.py", line 19, in get
    df = super().get(active_only=False, addnl_fields=addnl_fields,
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/engineobj.py", line 144, in get
    df = self.get_valid_df(self.iobj.table, **kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/engineobj.py", line 132, in get_valid_df
    table_df['timestamp'] = humanize_timestamp(table_df.timestamp)
  File "/home/jpietsch/suzieq/suzieq/utils.py", line 554, in humanize_timestamp
    return field.apply(lambda x: datetime.fromtimestamp(x/1000)) \
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/series.py", line 4212, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2403, in pandas._libs.lib.map_infer
  File "/home/jpietsch/suzieq/suzieq/utils.py", line 554, in <lambda>
    return field.apply(lambda x: datetime.fromtimestamp(x/1000)) \
TypeError: unsupported operand type(s) for /: 'str' and 'int'
------------------------------------------------------------
```

**Comment by ddutt** [comment]
I'm unable to reproduce the problem with the latest code. Could you please confirm?

**Comment by ddutt** [comment]
OK, I found the dataset to reproduce the problem. Fixing the issue
