### ISSUE TITLE
setting the analyzer to a timezone breaks bgp top

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#310]
**Describe the bug**
added to .suzieq/suzieq-cfg.yml
```
analyzer: { timezone: 'GMT' }
```
produces an exception:
```
(suzieq-QZqWZG2D-py3.8) jpietsch@jpietsch-server:~/suzieq$ suzieq/cli/suzieq-cli bgp top --what=updatesTx
Error running command: DatetimeArray subtraction must have the same timezones or no timezones
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/src/python-nubia/nubia/internal/cmdbase.py", line 482, in run_cli
    return fn(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/BgpCmd.py", line 152, in top
    df['estdTime'] = df['timestamp'] - humanize_timestamp(df.estdTime)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/ops/__init__.py", line 343, in wrapper
    result = arithmetic_op(lvalues, rvalues, op)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 186, in arithmetic_op
    res_values = op(lvalues, rvalues)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/arrays/datetimelike.py", line 1482, in __sub__
    result = self._sub_datetime_arraylike(other)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 663, in _sub_datetime_arraylike
    raise TypeError(
TypeError: DatetimeArray subtraction must have the same timezones or no timezones
------------------------------------------------------------
```

**Comment by jopietsch** [comment]
This was fixed last week.
