### ISSUE TITLE
after killing sq-poller, it spits out an exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#321]
**Describe the bug**
started sq-poller, ran it for a while, then killed it. it returned this traceback:
```
Traceback (most recent call last):
  File "suzieq/poller/sq-poller", line 419, in <module>
    asyncio.run(start_poller(userargs, cfg))
  File "/usr/lib/python3.8/asyncio/runners.py", line 46, in run
    _cancel_all_tasks(loop)
  File "/usr/lib/python3.8/asyncio/runners.py", line 61, in _cancel_all_tasks
    loop.run_until_complete(
  File "uvloop/loop.pyx", line 1454, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
```

**Comment by jopietsch** [comment]
I believe this does take multi control-Cs to produce this exception.
