### ISSUE TITLE
0 byte parquet file crashes sq-coalescer

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#330]
**Describe the bug**
0 byte file from the poller, gets an exception from the coalescer, which crashes. Because it's in ifCounters, only sqPoller is getting coalesced, all the other tables, including ifCounters aren't getting coalesced and are getting big.

I think after the coalescer crashes it doesn't restarted until I run restart sqpoller. I'm still checking that.

related to bug #57 

```
(suzieq-QZqWZG2D-py3.8) jpietsch@jpietsch-server:~/suzieq$ python3 suzieq/utilities/sq-coalescer.py
Traceback (most recent call last):
  File "suzieq/utilities/sq-coalescer.py", line 159, in <module>
    run_coalescer(cfg, tables, timestr, userargs.run_once,
  File "suzieq/utilities/sq-coalescer.py", line 59, in run_coalescer
    stats = do_coalesce(cfg, tables, period, logger, no_sqpoller)
  File "/home/jpietsch/suzieq/suzieq/db/dblib.py", line 79, in do_coalesce
    return dbeng.coalesce(tables, period, no_sqpoller)
  File "/home/jpietsch/suzieq/suzieq/db/parquet/parquetdb.py", line 340, in coalesce
    coalesce_resource_table(table_infolder, table_outfolder,
  File "/home/jpietsch/suzieq/suzieq/db/parquet/pq_coalesce.py", line 253, in coalesce_resource_table
    fdf = get_file_timestamps(dataset.files)
  File "/home/jpietsch/suzieq/suzieq/db/parquet/pq_coalesce.py", line 145, in get_file_timestamps
    ts = pd.read_parquet(file, columns=['timestamp'])
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/io/parquet.py", line 317, in read_parquet
    return impl.read(path, columns=columns, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/io/parquet.py", line 141, in read
    result = self.api.parquet.read_table(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pyarrow/parquet.py", line 1607, in read_table
    dataset = _ParquetDatasetV2(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pyarrow/parquet.py", line 1452, in __init__
    [fragment], schema=fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 761, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
OSError: Could not open parquet input source '/home/jpietsch/parquet-out//ifCounters/sqvers=1.0/namespace=dual-evpn/hostname=edge01/382acc0438424dc8954d5638083afb64.parquet': Invalid: Parquet file size is 0 bytes


```

**Comment by jopietsch** [comment]
after the coalescer crashes, it does not seem to restart, at least I look at the sq-coalescer.log and don't see anything after after an hour until I kill and restart the poller.

not that it would do any good, it would have just kept crashing over and over.

**Comment by jopietsch** [comment]
I deleted that 0 byte file and restated the poller. There is another 0 byte file, but this time the coalsecer crashes and then is restarted again about 20 seconds later and it crashes and this repeats forever. I don't know why the first one would crash and not restart.

the new 0 byte file is for another host

the error from the coalescer
```
(suzieq-QZqWZG2D-py3.8) jpietsch@jpietsch-server:~/suzieq$ python3 suzieq/utilities/sq-coalescer.py
Traceback (most recent call last):
  File "suzieq/utilities/sq-coalescer.py", line 159, in <module>
    run_coalescer(cfg, tables, timestr, userargs.run_once,
  File "suzieq/utilities/sq-coalescer.py", line 59, in run_coalescer
    stats = do_coalesce(cfg, tables, period, logger, no_sqpoller)
  File "/home/jpietsch/suzieq/suzieq/db/dblib.py", line 79, in do_coalesce
    return dbeng.coalesce(tables, period, no_sqpoller)
  File "/home/jpietsch/suzieq/suzieq/db/parquet/parquetdb.py", line 340, in coalesce
    coalesce_resource_table(table_infolder, table_outfolder,
  File "/home/jpietsch/suzieq/suzieq/db/parquet/pq_coalesce.py", line 253, in coalesce_resource_table
    fdf = get_file_timestamps(dataset.files)
  File "/home/jpietsch/suzieq/suzieq/db/parquet/pq_coalesce.py", line 145, in get_file_timestamps
    ts = pd.read_parquet(file, columns=['timestamp'])
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/io/parquet.py", line 317, in read_parquet
    return impl.read(path, columns=columns, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/io/parquet.py", line 141, in read
    result = self.api.parquet.read_table(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pyarrow/parquet.py", line 1607, in read_table
    dataset = _ParquetDatasetV2(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pyarrow/parquet.py", line 1452, in __init__
    [fragment], schema=fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 761, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
OSError: Could not open parquet input source '/home/jpietsch/parquet-out//ifCounters/sqvers=1.0/namespace=dual-evpn/hostname=exit02/5ffce143a14444278dc91356d8bb9f03.parquet': Invalid: Parquet file size is 0 bytes
```

**Comment by jopietsch** [comment]
not fixed
