### ISSUE TITLE
IOSXR branch, if I specify start or end-time I get an exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#343]
**Describe the bug**
```
(suzieq-QZqWZG2D-py3.8) jpietsch@jpietsch-server:~/suzieq$ time suzieq/cli/suzieq-cli bgp show --namespace=dual-evpn --start-time="yesterday"
Error running command: invalid literal for int() with base 10: 'c9881ac93b0c4835a2325c86425c11bb'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/nubia/internal/cmdbase.py", line 482, in run_cli
    return fn(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/BgpCmd.py", line 76, in show
    df = self.sqobj.get(
  File "/home/jpietsch/suzieq/suzieq/sqobjects/basicobj.py", line 151, in get
    return self.engine.get(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/bgp.py", line 36, in get
    df = super().get(addnl_fields=addnl_fields, **kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/engineobj.py", line 162, in get
    df = self.get_valid_df(self.iobj.table, **kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/engineobj.py", line 130, in get_valid_df
    table_df = self._dbeng.read(
  File "/home/jpietsch/suzieq/suzieq/db/parquet/parquetdb.py", line 117, in read
    cp_dataset = self._get_cp_dataset(table_name, need_sqvers, sqvers,
  File "/home/jpietsch/suzieq/suzieq/db/parquet/parquetdb.py", line 529, in _get_cp_dataset
    thistime = [int(x)*1000 for x in thistime]  # time in ms
  File "/home/jpietsch/suzieq/suzieq/db/parquet/parquetdb.py", line 529, in <listcomp>
    thistime = [int(x)*1000 for x in thistime]  # time in ms
ValueError: invalid literal for int() with base 10: 'c9881ac93b0c4835a2325c86425c11bb'
------------------------------------------------------------
```

**Comment by ddutt** [comment]
Closed with one of the many bug fixes.
