### ISSUE TITLE
'show version' fails under vSRX

### ISSUE THREAD

**Issue by Kircheneer** [netenglabs/suzieq#373]
**Describe the bug**
`show version` parsing under vSRX 3.0 produces a runtime error (see below).

**To Reproduce**
Run `sq-poller` with a vSRX 3.0 system in the inventory.

**Attach**
The following error is present in the sq-poller.log file.
```python
2021-05-05 15:08:54,444 - suzieq.poller.services.service - ERROR - Processing data failed for service device on node vsrx
Traceback (most recent call last):
  File "/home/leo/suzieq/venv/lib/python3.8/site-packages/suzieq/poller/services/service.py", line 654, in run
    result = self.process_data(output)
  File "/home/leo/suzieq/venv/lib/python3.8/site-packages/suzieq/poller/services/service.py", line 375, in process_data
    return self.clean_data(result, data)
  File "/home/leo/suzieq/venv/lib/python3.8/site-packages/suzieq/poller/services/service.py", line 432, in clean_data
    processed_data = dev_clean_fn(processed_data, raw_data)
  File "/home/leo/suzieq/venv/lib/python3.8/site-packages/suzieq/poller/services/device.py", line 98, in _clean_junos_data
    entry['bootupTimestamp'], int(raw_data[0]["timestamp"])/1000)/1000
KeyError: 'bootupTimestamp'
```

Output of the `show version` command:
```
vagrant@vsrx> show system uptime | display json
{
    "system-uptime-information" : [
    {
        "attributes" : {"xmlns" : "http://xml.juniper.net/junos/21.1R0/junos"},
        "current-time" : [
        {
            "date-time" : [
            {
                "data" : "2021-05-05 15:11:44 UTC",
                "attributes" : {"junos:seconds" : "1620227504"}
            }
            ]
        }
        ],
        "time-source" : [
        {
            "data" : " LOCAL CLOCK "
        }
        ],
        "system-booted-time" : [
        {
            "date-time" : [
            {
                "data" : "2021-05-05 14:23:55 UTC",
                "attributes" : {"junos:seconds" : "1620224635"}
            }
            ],
            "time-length" : [
            {
                "data" : "00:47:49",
                "attributes" : {"junos:seconds" : "2869"}
            }
            ]
        }
        ],
        "protocols-started-time" : [
        {
            "date-time" : [
            {
                "data" : "2021-05-05 14:31:45 UTC",
                "attributes" : {"junos:seconds" : "1620225105"}
            }
            ],
            "time-length" : [
            {
                "data" : "00:39:59",
                "attributes" : {"junos:seconds" : "2399"}
            }
            ]
        }
        ],
        "last-configured-time" : [
        {
            "date-time" : [
            {
                "data" : "2021-05-03 17:24:20 UTC",
                "attributes" : {"junos:seconds" : "1620062660"}
            }
            ],
            "time-length" : [
            {
                "data" : "1d 21:47",
                "attributes" : {"junos:seconds" : "164844"}
            }
            ],
            "user" : [
            {
                "data" : "root"
            }
            ]
        }
        ],
        "uptime-information" : [
        {
            "date-time" : [
            {
                "data" : "3:11PM",
                "attributes" : {"junos:seconds" : "1620227505"}
            }
            ],
            "up-time" : [
            {
                "data" : "48 mins",
                "attributes" : {"junos:seconds" : "2880"}
            }
            ],
            "active-user-count" : [
            {
                "data" : "1",
                "attributes" : {"junos:format" : "1 users"}
            }
            ],
            "load-average-1" : [
            {
                "data" : "4.00"
            }
            ],
            "load-average-5" : [
            {
                "data" : "3.78"
            }
            ],
            "load-average-15" : [
            {
                "data" : "4.21"
            }
            ],
            "user-table" : [
            {
            }
            ]
        }
        ]
    }
    ]
}
```

 **Expected behavior**
`show version` is processed properly.

**Screenshots**
Not applicable.

**Additional context**
Slack chat with Dinesh on the 5th May 2021~15:00 UTC

**Comment by ddutt** [comment]
Fixed with commit 8974791aeb8bba677b2cbf896aaaf160e8b0f8de
