### ISSUE TITLE
BGP table not displaying data

### ISSUE THREAD

**Issue by rishabhpanickar** [netenglabs/suzieq#397]
The BGP table is empty for an Arista EOS. 
```
root> bgp show hostname=ss
Empty DataFrame
Columns: [namespace, hostname, vrf, peer, peerHostname, state, afi, safi, asn, peerAsn, pfxRx, pfxTx, numChanges, estdTime, origPeer, peerIP, updateSource, active, timestamp]
Index: []

root> bgp assert hostname=ss
Empty DataFrame
Columns: [namespace, hostname, vrf, peer, afi, safi, asn, state, peerAsn, bfdStatus, reason, notificnReason, afisAdvOnly, afisRcvOnly, peerIP, updateSource, origPeer, active, timestamp, assert, assertReason]
Index: []
Assert passed
```
The BGP service was running fine (status: 200)

Error in /tmp/sqpoller.log:
```
2021-07-31 23:50:30,045 - suzieq.poller.services.service - ERROR - Processing data failed for service bgp on node ss
Traceback (most recent call last):
  File "/root/suzieq/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 659, in run
    result = self.process_data(output)
  File "/root/suzieq/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 376, in process_data
    return self.clean_data(result, data)
  File "/root/suzieq/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 433, in clean_data
    processed_data = dev_clean_fn(processed_data, raw_data)
  File "/root/suzieq/lib/python3.7/site-packages/suzieq/poller/services/bgp.py", line 77, in _clean_eos_data
    new_entry['hopsMax'] = int(entry.get('hopsMax', 255))-255
ValueError: invalid literal for int() with base 10: ''
```

**Comment by ddutt** [comment]
Fixed via commit 237bc3bd2b6fd0a13e365d48b20dc2457c799175
