### ISSUE TITLE
suzieq-gui does not exit gracefully when no config is present

### ISSUE THREAD

**Issue by zxiiro** [netenglabs/suzieq#445]
**Describe the bug**
When starting `suzieq-gui` with no configuration file the system does not appear to gracefully exit. It seems to sys.exit(1) but streamlit appears to still present a page and the terminal appears to still be running the process with the webserver on http://localhost:8501 reachable with an error message.

I think it would be better to gracefully exit when this happens and inform the user that they must present a config file for the service to work.

**To Reproduce**
1. Run `suzieq-gui` with no config file present

**Attach**

```
2021-10-10 10:25:29.203 Traceback (most recent call last):
  File "/Users/zxiiro/.virtualenvs/suzieq/lib/python3.8/site-packages/streamlit/caching.py", line 509, in get_or_create_cached_value
    return_value = _read_from_cache(
  File "/Users/zxiiro/.virtualenvs/suzieq/lib/python3.8/site-packages/streamlit/caching.py", line 308, in _read_from_cache
    raise e
  File "/Users/zxiiro/.virtualenvs/suzieq/lib/python3.8/site-packages/streamlit/caching.py", line 293, in _read_from_cache
    return _read_from_mem_cache(
  File "/Users/zxiiro/.virtualenvs/suzieq/lib/python3.8/site-packages/streamlit/caching.py", line 212, in _read_from_mem_cache
    raise CacheKeyNotFoundError("Key not found in mem cache")
streamlit.caching.CacheKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zxiiro/.virtualenvs/suzieq/lib/python3.8/site-packages/streamlit/script_runner.py", line 350, in _run_script
    exec(code, module.__dict__)
  File "/Users/zxiiro/src/github.com/netenglabs/suzieq/suzieq/gui/suzieq-gui.py", line 118, in <module>
    apprun()
  File "/Users/zxiiro/src/github.com/netenglabs/suzieq/suzieq/gui/suzieq-gui.py", line 114, in apprun
    state.pages[page](state)
  File "/Users/zxiiro/src/github.com/netenglabs/suzieq/suzieq/gui/pages/status.py", line 61, in page_work
    draw_sidebar_status(state, state_container.sqobjs)
  File "/Users/zxiiro/src/github.com/netenglabs/suzieq/suzieq/gui/pages/status.py", line 23, in draw_sidebar_status
    devdf = gui_get_df(sqobjs['device'], columns=['namespace', 'hostname'])
  File "/Users/zxiiro/.virtualenvs/suzieq/lib/python3.8/site-packages/streamlit/caching.py", line 545, in wrapped_func
    return get_or_create_cached_value()
  File "/Users/zxiiro/.virtualenvs/suzieq/lib/python3.8/site-packages/streamlit/caching.py", line 527, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
  File "/Users/zxiiro/src/github.com/netenglabs/suzieq/suzieq/gui/guiutils.py", line 46, in gui_get_df
    df = sqobject(view=view, start_time=stime, end_time=etime) \
  File "/Users/zxiiro/src/github.com/netenglabs/suzieq/suzieq/sqobjects/device.py", line 8, in __init__
    super().__init__(table='device', **kwargs)
  File "/Users/zxiiro/src/github.com/netenglabs/suzieq/suzieq/sqobjects/basicobj.py", line 36, in __init__
    self.ctxt = SqContext(engine_name, config_file)
  File "/Users/zxiiro/src/github.com/netenglabs/suzieq/suzieq/sqobjects/basicobj.py", line 12, in __init__
    self.cfg = load_sq_config(config_file=config_file)
  File "/Users/zxiiro/src/github.com/netenglabs/suzieq/suzieq/utils.py", line 144, in load_sq_config
    sys.exit(1)
SystemExit: 1
```

 **Expected behavior**

Daemon service exits gracefully with appropriate error message rather than requiring the user to additionally ctrl+c to terminate the process.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ddutt** [comment]
Fixed. Try version 0.17.1
