### ISSUE TITLE
IPv4 Labeled unicast AFI/SAFI raises an exception in poller/services/bgp.py

### ISSUE THREAD

**Issue by m1009d** [netenglabs/suzieq#476]
**Describe the bug**

Suzieq raises `ValueError: too many values to unpack (expected 2)` error when `inet-labeled-unicast` is configured on Junos device.

https://github.com/netenglabs/suzieq/blob/85e7cddd380440b1f52ed501df956e117e5513f7/suzieq/poller/services/bgp.py#L200

**To Reproduce**

    - create bgp configuration
    - poll the data with suzieq
    - see the error in the `/tmp/sq-poller.log`

```py
root@addb252f553c:/suzieq# tail -f /tmp/sq-poller.log 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 694, in run
    result = self.process_data(output)
  File "/usr/local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 419, in process_data
    return self.clean_data(result, data)
  File "/usr/local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 476, in clean_data
    processed_data = dev_clean_fn(processed_data, raw_data)
  File "/usr/local/lib/python3.7/site-packages/suzieq/poller/services/bgp.py", line 200, in _clean_junos_data
    afi, safi = elem.split()
ValueError: too many values to unpack (expected 2)
```

Example of data which is stored in the `entry` variable:

```py
{'rrclient': False, 'peerIP': '10.255.1.2', 'peer': '10.255.1.2', 'peerAsn': 65501, 'updateSource': '10.255.1.1', 'asn': 64800, 'state': 'Established', 'reason': 'None', 'v4EgressRmap': 'spine-lu-EBGP-out-v4', 'v4IngressRmap': 'spine-lu-EBGP-in-v4', 'holdTime': 90, 'afiSafiAdvList': 'inet-labeled-unicast', 'bfdStatus': 'disabled', '_bfdAdmin': 'disabled', 'afiSafiEnabledList': 'inet-labeled-unicast', 'afiSafiRcvList': 'inet-labeled-unicast', 'notificnReason': '', 'numChanges': 0, 'peerRouterId': '1.1.2.1', 'routerId': '192.168.0.11', 'keepaliveTime': 30, 'ifname': 'ae1.0', '_pfxTxList': ['1'], '_pfxRxList': ['13'], '_pfxSuppressList': ['0'], '_pfxBestRxList': ['2'], '_pfxType': ['inet.0'], 'updatesRx': 0, 'updatesTx': 1, '_tableNameList': ['inet.0'], '_tableAfiList': ['inet-labeled-unicast'], '_entryType': 'neighbors', 'estdTime': 1633422266867, 'afisAdvOnly': [], 'afisRcvOnly': []}
```

Example of data which is stored in the `elem` variable:

```py
ipv4 labeled unicast
```

Example of data which is stored in the `orig_elem` variable:

```py
inet-labeled-unicast
```

**Expected behavior**
The code should be able to handle the `inet-labeled-unicast` AFI/SAFI.

https://github.com/netenglabs/suzieq/blob/85e7cddd380440b1f52ed501df956e117e5513f7/suzieq/poller/services/bgp.py#L200

**Comment by ddutt** [comment]
The fix has been released as part of the 0.16.0 alpha. Please test and let me know.
