### ISSUE TITLE
Poller Stalls After Device Reboots

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#480]
**Describe the bug**
After devices are rebooted the poller stalls. 
Behaviour seen:
* All devices showed alive.
* I rebooted my EVENG box.
* All devices but 3 came back online in Sq.
* No activity in poller log after seeing...
```
2021-11-18 21:05:11,638 - suzieq.poller.services.service - ERROR - Processing data failed for service ospfNbr on node leaf2-ios
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 692, in run
    result = self.process_data(output)
  File "/usr/local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 418, in process_data
    return self.clean_data(result, data)
  File "/usr/local/lib/python3.7/site-packages/suzieq/poller/services/service.py", line 475, in clean_data
    processed_data = dev_clean_fn(processed_data, raw_data)
  File "/usr/local/lib/python3.7/site-packages/suzieq/poller/services/ospfNbr.py", line 140, in _clean_ios_data
    entry['lastUpTime'] = parse(entry['lastUpTime']).timestamp()
AttributeError: 'NoneType' object has no attribute 'timestamp'
```

**To Reproduce**
Reboot device and view `device show`

**Attach**
Main exception above. 

 **Expected behaviour**
Poller reties the device and repolls.

**Comment by ddutt** [comment]
@rickdonato I'm going to close this bug unless you can reproduce it. Please test it with the 0.18.0RC1 thats going out later today
