### ISSUE TITLE
Top returns an error

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#635]
**Describe the bug**
`top` returns an error.

**To Reproduce**
```
rick> bgp top what=numChanges
Error running command: 'numChanges'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rick/development/course-dev/suzieq-bootcamp/venv/venv-sq-bootcamp/lib/python3.8/site-packages/nubia/internal/cmdbase.py", line 408, in run_interactive
    ret = fn(**args_dict)
  File "/home/rick/development/course-dev/suzieq-bootcamp/venv/venv-sq-bootcamp/lib/python3.8/site-packages/suzieq/cli/sqcmds/command.py", line 279, in top
    return self._gen_output(df.sort_values(by=[what], ascending=False),
  File "/home/rick/development/course-dev/suzieq-bootcamp/venv/venv-sq-bootcamp/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/rick/development/course-dev/suzieq-bootcamp/venv/venv-sq-bootcamp/lib/python3.8/site-packages/pandas/core/frame.py", line 6259, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/home/rick/development/course-dev/suzieq-bootcamp/venv/venv-sq-bootcamp/lib/python3.8/site-packages/pandas/core/generic.py", line 1779, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'numChanges'
------------------------------------------------------------
```

**Attach**
TBC

 **Expected behavior**
TBC

**Screenshots**
TBC

**Additional context**
Environment from which this is occurring in:
* remote cli is being used
* correct port setting applied via "set rest-server-port=443"
* can successfully query other tables. For example "device show"

**Local DB works, but remote dosn't**

**Comment by ddutt** [comment]
Fixed in 0.17.1, via commit 06507652eac6888ea808cd574fb0c0f9906fc42e
