### ISSUE TITLE
aiohttp TypeError

### ISSUE THREAD

**Issue by PieterL75** [netenglabs/suzieq#656]
**Describe the bug**
After a clean install using pip/venv I got an TypeError raised from aiohttp.
```
Traceback (most recent call last):
  File "/home/pieterl/suzieq/suzieq/poller/sq_poller.py", line 183, in controller_main
    asyncio.run(start_controller(args, cfg))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/pieterl/suzieq/suzieq/poller/sq_poller.py", line 39, in start_controller
    controller = Controller(user_args, config_data)
  File "/home/pieterl/suzieq/venv/lib/python3.8/site-packages/suzieq/poller/controller/controller.py", line 40, in __init__
    self._base_plugin_classes = ControllerPlugin.get_plugins()
  File "/home/pieterl/suzieq/venv/lib/python3.8/site-packages/suzieq/shared/sq_plugin.py", line 80, in get_plugins
    mod = import_module(mname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pieterl/suzieq/venv/lib/python3.8/site-packages/suzieq/poller/controller/source/netbox.py", line 14, in <module>
    import aiohttp
  File "/home/pieterl/suzieq/venv/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/pieterl/suzieq/venv/lib/python3.8/site-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/home/pieterl/suzieq/venv/lib/python3.8/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/home/pieterl/suzieq/venv/lib/python3.8/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/home/pieterl/suzieq/venv/lib/python3.8/site-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

**To Reproduce**
1. Fresh python 3.8
2. create venv
3. create suzieq-cfg.yml
4. create inventory.yml
5. run sq-poller

 **Expected behavior**
Clear run

**Additional context**
Seems that the `async-timeout-4.0.2` package was installed.
aiohttp is not compatible with that and needs async-timeout < 4.0

a simple `pip install aiohttp` removed the 4.0.2 and installed the 3.0.1

Is the 4.0 somewere in a requirements.txt, or is this just my system that had the wrong one installed

**Comment by PieterL75** [comment]
Cool. Then I'll close this BR.
Hopefully it helps someone later that has the same problem.

Thx for confirming!

Pieter
