### ISSUE TITLE
[Bug]: suzieq installed in pipx virtualenv using python3.8,python3.9 stating missing import uvloop

### ISSUE THREAD

**Issue by heathdbrown** [netenglabs/suzieq#892]
### Suzieq version

0.20.1

### Install Type

hand deployed python

### Python version

3.8

### Impacted component

sq-poller

### Steps to Reproduce

# RHEL7 or CENTOS7
- Install build tools

```bash
sudo yum install -y openssl-devel openssl11-devel openssl11-lib gcc-c++ wget make cmake gcc bzip2-devel libffi-devel zlib-devel
```

- Install pipx
```bash
sudo /usr/bin/python3.6 -m pip install pipx
```

- Install pyenv
```bash
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
```

- install newer python versions

```bash
CPPFLAGS=$(pkg-config --cflags openssl11) LDFLAGS=$(pkg-config --libs openssl11) pyenv install 3.8 or pyenv install 3.9
```

-  install suzieq via pipx
```bash
PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin PIPX_DEFAULT_PYTHON=/opt/software/pyenv/versions/3.8.16/bin/python pipx install --include-deps suzieq
```
-  Configure with basic configuration for suizeq in ~.suzieq
- Attempt to run sq-poller

### Expected Behavior

sq-poller -I ~/.suzieq/inventory.yaml
<normal operations>

### Observed Behavior

```bash
$ sq-poller -I ~/.suzieq/inventory.yaml
2023-05-12 17:17:24,629 - suzieq.poller.controller - WARNING - log level WARNING
2023-05-12 17:17:24,630 - suzieq.poller.controller - INFO -
|-----------------------------------------------------|
SuzieQ Poller Controller v0.20.1
Python version: 3.8.16 (default, May 12 2023, 14:48:23)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Platform: Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.2.5
CPU: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz 4 cores - freq. 0.00Mhz - 0.00Mhz
CPU load 1m, 5m, 15m: 4.5%, 1.5%, 1.5%
Memory: total: 8369795072, available: 7309295616
|-----------------------------------------------------|
2023-05-12 17:17:24,631 - suzieq.poller.controller - WARNING - Minimum recommended system spec is a modern i7-equivalent or higher with 4 cores and 16 GB RAM
[COALESCER]:   File "/opt/pipx/venvs/suzieq/lib/python3.8/site-packages/suzieq/utilities/sq_coalescer.py", line 26
[COALESCER]:     def validate_periodstr(periodstr: str) -> Tuple[bool, str]:
[COALESCER]:                                     ^
[COALESCER]: SyntaxError: invalid syntax
2023-05-12 17:17:24,915 - suzieq.poller.worker.coalescer_launcher - WARNING - Restarting the coalescer
[WORKER 0]: Traceback (most recent call last):
[WORKER 0]:   File "/opt/pipx/venvs/suzieq/lib/python3.8/site-packages/suzieq/poller/worker/sq_worker.py", line 10, in <module>
[WORKER 0]:     import uvloop
[WORKER 0]: ModuleNotFoundError: No module named 'uvloop'
2023-05-12 17:17:24,951 - suzieq.poller.controller - ERROR - Unexpected worker 0 death:None
2023-05-12 17:17:24,952 - suzieq.poller.worker.coalescer_launcher - WARNING - Waiting coalescer termination...
/
/
```

**Comment by heathdbrown** [comment]
I did verify that uvloop is in the virtualenv created by pipx.

```bash
# python -m pip list | grep uvloop
uvloop               0.17.0
```
